### ISSUE TITLE
script-base v0.0.12: Unknown build error

### ISSUE THREAD

**Issue by enzy** [manGoweb/npm#26]
mango-cli: 3.6.0
TypeScript: 3.7.2

Verze script-base v0.0.12 při kompilaci vždy selže na:
```
Unhandled rejection Error: Debug Failure. No error for last overload signature
    at resolveCall (C:\Work\mango-cli\node_modules\typescript\lib\typescript.js:55202:38)
    at resolveCallExpression (C:\Work\mango-cli\node_modules\typescript\lib\typescript.js:55548:20)
    at resolveSignature (C:\Work\mango-cli\node_modules\typescript\lib\typescript.js:55904:28)
    at getResolvedSignature (C:\Work\mango-cli\node_modules\typescript\lib\typescript.js:55935:26)
    at checkCallExpression (C:\Work\mango-cli\node_modules\typescript\lib\typescript.js:56017:29)
    at checkExpressionWorker (C:\Work\mango-cli\node_modules\typescript\lib\typescript.js:58295:28)
    at checkExpression (C:\Work\mango-cli\node_modules\typescript\lib\typescript.js:58205:38)
    at checkExpressionStatement (C:\Work\mango-cli\node_modules\typescript\lib\typescript.js:60582:13)
    at checkSourceElementWorker (C:\Work\mango-cli\node_modules\typescript\lib\typescript.js:62990:28)
    at checkSourceElement (C:\Work\mango-cli\node_modules\typescript\lib\typescript.js:62873:17)
    at Object.forEach (C:\Work\mango-cli\node_modules\typescript\lib\typescript.js:309:30)
    at checkSourceFileWorker (C:\Work\mango-cli\node_modules\typescript\lib\typescript.js:63191:20)
    at checkSourceFile (C:\Work\mango-cli\node_modules\typescript\lib\typescript.js:63163:13)
    at getDiagnosticsWorker (C:\Work\mango-cli\node_modules\typescript\lib\typescript.js:63238:17)
    at Object.getDiagnostics (C:\Work\mango-cli\node_modules\typescript\lib\typescript.js:63224:24)
    at C:\Work\mango-cli\node_modules\typescript\lib\typescript.js:95842:85
```

Downgrade na script-base v0.0.10 chybu kompilace eliminuje.

**Comment by Onset** [comment]
Jako dočasný workaround na projektech, kde je `scripts-base`, se stačí vrátit k `mango-cli@3.5.0`.

**Comment by enzy** [comment]
@Onset Nebo jak píšu udělat downgrade script-base na v0.0.10.

**Comment by enzy** [comment]
Nejsme sami https://github.com/microsoft/TypeScript/issues/35186

**Comment by enzy** [comment]
Minimal test case: https://github.com/enzy/ts-scriptsbase-debug-failure
